from typing import Tuple


def verify(input_file: str, solution_file: str) -> Tuple[bool, str]:
    """
    Verification function: checks if all the constraints are satisfied.
    Please do NOT change the function name. You can take in more than one input file, but please keep the last argument as the solution file.
    It is used by the agent to verify the output of the solver.

    Args:
        input_file: Path to the input file
        solution_file: Path to the output file generated by the solver

    Returns:
        Tuple[bool, str]: A tuple of (is_valid, error_message)
            - is_valid: True if the output is valid, False otherwise
            - error_message: If the output is invalid, please provide a detailed error message on why it is invalid;
            If the output is valid, please return an empty string.

    """
    # inputs = parse_input(input_file)
    # outputs = parse_output(solution_file)
    raise NotImplementedError("This is a placeholder implementation.")
